### ISSUE TITLE
Module doesn't work on PbtA 0.8+

### ISSUE THREAD

**Issue by mclemente** [gonzaPaEst/root#2]
Hello, I'm a dev of PbtA and its 0.8 update broke your module due to refactoring.

One is caused by calling `PbtaUtility.isEmpty` which was removed in favor of `foundry.utils.isEmpty`.

The other issue is caused by importing `PbtaRolls`, which was removed in favor of `RollPbtA`, which is an actual Roll class instead of a class with methods that make rolls like before.

At a glance, I am not sure what is the difference from your wrap of `PbtaRolls.rollMoveExecute`, but if you were to remove it, the module would run without issue for now.

A little heads-up: the next major release of PbtA will probably break your RootTraitsSheet due to another refactor, but once that is released. That update should come only in January or later.
You should expect no more breaking changes once that is done, and you won't need to import `PbtaItemSheet` anymore and will be able to call it directly from `game.pbta.applications.item.PbtaItemSheet`.

**Comment by emergentstories** [comment]
Actually, removing the rollMoveExecute ends up breaking the rolls logic. I will have to rebuild it. Thanks!
